### ISSUE TITLE
ES6 babel project: Cannot read property 'reduce' or 'forEach' of undefined

### ISSUE THREAD

**Issue by kristianmandrup** [documentationjs/gulp-documentation#23]
Running on an ES6 project using babel.

```
[19:18:50] Finished 'documentation' after 792 ms
/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/lib/output/markdown_ast.js:125
  return callback(null, u('root', comments.reduce(function (memo, comment) {
                                          ^

TypeError: Cannot read property 'reduce' of undefined
    at commentsToAST (/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/lib/output/markdown_ast.js:125:43)
    at module.exports (/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/lib/output/markdown.js:19:3)
    at DestroyableTransform.<anonymous> (/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/gulp-documentation/index.js:79:7)
    at /Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/index.js:83:14
    at Deps.<anonymous> (/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/lib/input/dependency.js:38:12)
    at Deps.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Deps.emit (events.js:188:7)
    at Babelify.<anonymous> (/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/module-deps/index.js:239:18)
    at emitOne (events.js:101:20)
```

If I drop the markdown task:

```
[19:21:45] Finished 'documentation' after 1.33 s
/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/lib/walk.js:10
  comments.forEach(function (comment) {
          ^

TypeError: Cannot read property 'forEach' of undefined
    at walk (/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/lib/walk.js:10:11)
    at makeHTML (/Users/kristianmandrup/repos/node-libs/nodelib-2017/node_modules/documentation/lib/output/html.js:49:14)
```

**Comment by tmcw** [comment]
Thanks for the bug report, I'll check this out today!

**Comment by tmcw** [comment]
Same as #17
