### ISSUE TITLE
Documentation generation order throws unexpected error.

### ISSUE THREAD

**Issue by silviogreuel** [documentationjs/gulp-documentation#7]
Given default example,
but changing doc generation order,
HTML before MARKDOWN,
~~~~
var documentation = require('documentation'),
    gulp = require('gulp');
 
gulp.task('documentation', function () {
 gulp.src('./index.js')
    .pipe(documentation({ format: 'html' }))
    .pipe(gulp.dest('html-documentation'));
 
  gulp.src('./index.js')
    .pipe(documentation({ format: 'md' }))
    .pipe(gulp.dest('md-documentation'));
   
  gulp.src('./index.js')
    .pipe(documentation({ format: 'json' }))
    .pipe(gulp.dest('json-documentation'));
 
});
~~~~

Causes unexpected error
~~~~
......project/node_modules/gulp-documentation/node_modules/documentation/streams/output/markdown.js:55
  if (!this.params) return '';
           ^
TypeError: Cannot read property 'params' of undefined
    at formatParameters (......project/node_modules/gulp-documentation/node_modules/documentation/streams/output/markdown.js:55:12)
    at Object.<anonymous> (......project/node_modules/gulp-documentation/node_modules/documentation/streams/output/markdown.js:87:38)
    at Object.eval (eval at createFunctionContext (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:14:229)
    at ret (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at Object.invokePartial (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/runtime.js:218:12)
    at Object.invokePartialWrapper [as invokePartial] (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/runtime.js:61:39)
    at Object.eval (eval at createFunctionContext (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:5:26)
    at prog (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/runtime.js:193:15)
    at execIteration (......project/node_modules/gulp-documentation/node_modules/documentation/node_modules/handlebars/dist/cjs/handlebars/base.js:155:19)
~~~~

**Comment by tmcw** [comment]
@silviogreuel can you update to gulp-documentation 2.0.0 and see if this error recurs?

**Comment by silviogreuel** [comment]
@tmcw all of my 5 projects tested and working on 2.0.0, gw...

**Comment by tmcw** [comment]
:+1:
